# Generated by Django 4.2.4 on 2024-03-13 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_doctor_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('date_of_birth', models.DateField()),
                ('isMale', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='certificateImage',
            new_name='certificateUrl',
        ),
        migrations.AddField(
            model_name='doctor',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DiseasesExternalLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('link', models.CharField(max_length=2000)),
                ('diseaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='approvingAdminId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.admin'),
        ),
    ]
