# Generated by Django 4.2.4 on 2024-03-13 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_admin_disease_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('imageUrl', models.ImageField(upload_to='medicine_images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='DiseasesExternalLinks',
            new_name='DiseaseExternalLink',
        ),
        migrations.CreateModel(
            name='DiseaseMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
                ('medicineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicine')),
            ],
        ),
    ]
