# Generated by Django 4.2.4 on 2024-03-13 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_medicine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
