# Generated by Django 4.2.4 on 2024-03-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_admin_password_alter_doctor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='isMale',
            field=models.BooleanField(),
        ),
    ]
