# Generated by Django 4.2.4 on 2024-03-13 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_patient_ismale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
