# Generated by Django 4.2.4 on 2024-03-13 13:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_date_of_birth_patient_dateofbirth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosisDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('diseaseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.disease')),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patient')),
            ],
        ),
    ]
