# Generated by Django 4.2.4 on 2024-03-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_patientdiagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('datasetName', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='disease',
            name='datasetName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='PatientDiagnosisSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientDiagnosisId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.patientdiagnosis')),
                ('symptomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.symptom')),
            ],
        ),
    ]
