# Generated by Django 4.2.4 on 2024-03-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_symptom_disease_datasetname_patientdiagnosissymptom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='datasetName',
            field=models.CharField(max_length=100),
        ),
    ]
