# Generated by Django 4.2.4 on 2024-03-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_disease_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptom',
            name='datasetName',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='symptom',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
