# Generated by Django 4.2.4 on 2024-03-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_symptom_datasetname_alter_symptom_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
