# Generated by Django 4.2.4 on 2024-03-19 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_first_name_admin_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('taken', 'Taken'), ('ended', 'Ended')], default='pending', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='patientdiagnosis',
            name='isSubmittedForFurtherFollowup',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MedicalCaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=150)),
                ('urgencyLevel', models.CharField(choices=[('normal', 'Normal'), ('critical', 'Critical')], default='normal', max_length=100)),
                ('caseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.medicalcase')),
            ],
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='diagnosisId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.patientdiagnosis'),
        ),
        migrations.AddField(
            model_name='medicalcase',
            name='takenBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.doctor'),
        ),
    ]
