# Generated by Django 4.2.4 on 2024-03-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_medicalcase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcasemessage',
            name='senderIsDoctor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
