# Generated by Django 4.2.4 on 2024-03-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_medicalcasemessage_senderisdoctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseexternallink',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
