# Generated by Django 4.2.4 on 2024-04-02 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_diseaseexternallink_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='careerStartDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='doctor',
            name='isMale',
            field=models.BooleanField(default=True),
        ),
    ]
