# Generated by Django 4.2.4 on 2024-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_doctor_careerstartdate_doctor_ismale'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaseexternallink',
            name='brief',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='diseaseexternallink',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='external_links'),
        ),
    ]
