# Generated by Django 4.2.4 on 2024-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_diseaseexternallink_brief_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseexternallink',
            name='brief',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='careerStartDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='isMale',
            field=models.BooleanField(),
        ),
    ]
