# Generated by Django 4.2.4 on 2024-04-12 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_diseaseexternallink_brief_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalcasemessage',
            name='sentAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
